[tool.poetry]
name = "purr"
version = "0.1.0"
description = ""
authors = ["Pete-Louise <pete.asclepiadoideae@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
typer = "^0.9.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
